update
upgrade

tap homebrew/versions
tap phinze/homebrew-cask
tap homebrew/binary
tap caskroom/versions
# ricty
tap sanemat/font

# 各種インストール
install openssl cmake wget curl libtool ctags vim zsh tmux ag tree git tig 
install fish automake z dnsmasq composer jq sbt 
install rbenv ruby-build vimgit sl mysql ricty
install heroku-toolbelt imagemagick pdftk w3m
install mtr #extend traceroute
install htop #extend top
install dfc #extend df
# mount
install fuse4x-kext osxfuse sshfs

install brew-cask

cask install iterm2
cask install alfred
cask install appcode
cask install dash
cask install hipchat
cask install skitch
cask install evernote
cask install skype
cask install sourcetree
cask install mysqlworkbench
cask install sequel-pro
cask install google-chrome
cask install google-japanese-ime
cask install firefox
cask install yorufukurou
cask install kobito
cask install virtualbox
cask install vagrant
cask install shiftit
cask install sublime-text
cask install eclipse-ide
cask install magican
cask install the-unarchiver
cask install imageoptim
cask install speedlimit
cask install colors
cask install clipmenu
cask install sitesucker
cask install github
cask install omnifocus
cask install keyremap4macbook
cask install pckeyboardhack
cask install appcleaner
cask install openoffice
cask install remote-desktop-connection
cask install hyperswitch
cask install gitter
cask install sequel-pro

# 不要なファイルを削除
cleanup
