update
upgrade

tap homebrew/versions
tap phinze/homebrew-cask
tap homebrew/binary
# ricty
tap sanemat/font

# 各種インストール
install brew-cask
install rbenv ruby-build zsh vimgit sl ctags mysql tmux openssl ricty cmake fish wget curl cmake libtool automake tig ag z dnsmasq composer jq

cask install iterm2
cask install alfred
cask install appcode
cask install dash
cask install skitch
cask install evernote
cask install skype
cask install sourcetree
cask install mysqlworkbench
cask install sequel-pro
cask install google-chrome
cask install google-japanese-ime
cask install firefox
cask install yorufukurou
cask install kobito
cask install virtualbox
cask install vagrant
cask install sublime-text
cask install eclipse-ide
cask install magican
cask install the-unarchiver
cask install imageoptim
cask install speedlimit
cask install colors
cask install clipmenu
cask install sitesucker
cask install github
cask install omnifocus
cask install keyremap4macbook
cask install pckeyboardhack
cask install appcleaner
cask install openoffice
cask install remote-desktop-connection
